
gateway:
  name: shared-gateway
  namespace: infra
  address: public-static-ip
  hosts:
    - name: linkthis-cc-https
      hostname: linkthis.cc
      tls: cloudflare-origin-ssl
    - name: wildcard-linkthis-cc-https
      hostname: "*.linkthis.cc"
      tls: cloudflare-origin-ssl
